---
# Common labels
- name: bug
  description: Something isn't working.
  color: d73a4a
- name: duplicate
  description: This issue or pull request already exists.
  color: cfd3d7
- name: WIP
  description: This pull request is in Work In Progress state.
  color: ff0000
- name: stale
  description: No activity for at least 30 days.
  color: ffccef
- name: enhancement
  description: New feature or request
  color: a2eeef
- name: help wanted
  description: Extra attention is needed
  color: 008672
- name: invalid
  description: This doesn't seem right
  color: e4e669
- name: question
  description: Further information is requested
  color: d876e3
- name: tech-debt
  description: Tech debt
  color: ADE720
- name: github_actions
  description: Pull requests that update Github_actions code
  color: 000000
- name: dependencies
  description: Pull requests that update a dependency file
  color: 0366d6

# Language labels
- name: go
  description: Pull requests that update Go code
  color: 16e2e2
- name: javascript
  description: Pull requests that update Javascript code
  color: 168700
- name: python
  description: Pull requests that update Python code
  color: C2264B
- name: docker
  description: Pull requests that update Docker code
  color: 21ceff

# Scope labels
- name: scope/ci
  description: Improvements or additions to CI.
  color: 0075ca
- name: scope/documentation
  description: Improvements or additions to documentation.
  color: 0075ca
- name: scope/setup
  description: Improvements or additions to Setup files.
  color: 0075ca

# Sizing labels
- name: size/XS
  description: Denotes a PR that changes 0-9 lines.
  color: 009900
- name: size/S
  description: Denotes a PR that changes 10-29 lines.
  color: 77bb00
- name: size/M
  description: Denotes a PR that changes 30-99 lines.
  color: eebb00
- name: size/L
  description: Denotes a PR that changes 100-499 lines.
  color: ee9900
- name: size/XL
  description: Denotes a PR that changes 500-999 lines.
  color: ee5500
- name: size/XXL
  description: Denotes a PR that changes 1000+ lines.
  color: ee0000