---
scope/ci:
  - .github/**/*
scope/documentation:
  - docs/**/*
scope/setup:
  - requirements.txt

# Language label paths
javascript:
  - ./**/*.js
python:
  - ./**/*.python
golang:
  - ./**/*.go
docker:
  - ./**/*Dockerfile
  