name: lychee

on:
  push:
    branches:
      - "main"
    paths:
      - "docs/**"
  pull_request:
    paths:
      - "docs/**"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: lychee
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        with:
          # Check all markdown and html files in doc folder
          args: --verbose --no-progress './docs/docs/**/*.md'
          # Fail action on broken links
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
