---
name: conventional-title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  run:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: aslafy-z/conventional-pr-title-action@2ce59b07f86bd51b521dd088f0acfb0d7fdac55e
        with:
          preset: conventional-changelog-angular@^5.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
