---
name: label-diff

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  size:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@bbbaa0d5ccce8e2e76254560df5c64b82dac2e12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  paths:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler-paths.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
